{% set name = "libcbm" %}
{% set version = "2.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/py3/l/libcbm/libcbm-{{ version }}-py3-none-any.whl
  sha256: 97c845cc6d8fbf642d617519b13116d75f0796cd5df14bcec53a749dbecff115

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv"

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - pandas
    - scipy
    - numexpr
    - numba
    - pyyaml
    - mock
    - openpyxl

test:
  imports:
    - libcbm

about:
  home: https://github.com/cat-cfs/libcbm_py
  summary: Carbon Budget Modeling tools for forest ecosystem simulation
  license: GPL-3.0-or-later
  license_family: GPL

extra:
  recipe-maintainers:
    - gparadis